#!/usr/bin/env python

from pathlib import Path
import os

for tagpath in (Path.cwd() / 'plots').glob('*/'):
    tag = tagpath.stem
    paths = {}
    for path in tagpath.glob('window_length_*'):
        size = int(path.stem.split('_')[-1])
        paths[(path / 'window_stepsize_2' / 'low_res_rgb.pdf').absolute()
              ] = size
    paths = sorted(paths.keys(), key=lambda p: paths[p])

    command = 'pdfunite ' + ' '.join(
        [p.as_posix() for p in paths]
    ) + f' summary_{tag}.pdf'
    os.system(command)
